# Generated by Django 5.1.2 on 2024-10-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djpress", "0004_rename_name_category_title_category_menu_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="djpress.post",
            ),
        ),
    ]
