# Generated by Django 5.2 on 2025-04-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djpress", "0011_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
