# Generated by Django 5.2 on 2025-04-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djpress", "0012_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="The slug is automatically generated from the title, or from the first 5 words of the content if no title.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, help_text="Title is only required for pages.", max_length=200),
        ),
    ]
