# Generated by Django 5.2 on 2025-05-03 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djpress", "0013_alter_post_slug_alter_post_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date",
            new_name="published_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="modified_date",
            new_name="updated_at",
        ),
    ]
