# Generated by Django 5.2 on 2025-05-03 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djpress", "0014_rename_date_post_published_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"ordering": ["-uploaded_at"], "verbose_name": "Media", "verbose_name_plural": "Media"},
        ),
        migrations.RenameField(
            model_name="media",
            old_name="modified_date",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="date",
            new_name="uploaded_at",
        ),
    ]
