# Generated by Django 5.2 on 2025-05-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djpress", "0015_alter_media_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="_date",
            field=models.DateField(
                blank=True,
                help_text="Date that the post was published, without any timezone information. Used for generating the URL.",
                null=True,
            ),
        ),
    ]
