# Generated by Django 5.2.7 on 2025-11-07 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djpress", "0017_populate_post__date_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["title"], name="djpress_post_title_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["content"], name="djpress_post_content_idx"),
        ),
    ]
