# Generated by Django 6.0.5 on 2026-06-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djpress", "0018_post_djpress_post_title_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "setting",
                "verbose_name_plural": "settings",
            },
        ),
    ]
