# Generated by Django 6.0.6 on 2026-06-06 05:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djpress", "0019_setting"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="djpress_post_content_idx",
        ),
    ]
