# Generated by Django 6.0.6 on 2026-06-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djpress", "0020_remove_post_djpress_post_content_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when this post/page was soft-deleted.",
                null=True,
                verbose_name="Deleted At",
            ),
        ),
    ]
