# Generated by Django 5.2.15 on 2026-06-14 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djpress", "0021_post_deleted_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={
                "ordering": ["-uploaded_at"],
                "permissions": [("change_other_media", "Can change other users' media")],
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "default_manager_name": "admin_objects",
                "permissions": [
                    ("can_publish_post", "Can publish post"),
                    ("change_other_post", "Can change other users' posts"),
                    ("can_soft_delete_post", "Can soft-delete post"),
                    ("can_restore_post", "Can restore post"),
                    ("can_hard_delete_post", "Can hard-delete post"),
                ],
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
    ]
