[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "djpress"
version = "0.31.0"
description = "A blog application for Django sites, inspired by classic WordPress."
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Stuart Maxwell", email = "stuart@amanzi.nz" }]
dependencies = ["django>=5.2.0,<6.2", "markdown>=3.7"]
license = { file = "LICENSE" }
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Framework :: Django :: 5.2",
  "Framework :: Django :: 6.0",
  "Framework :: Django :: 6.1",
  "Intended Audience :: Developers",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
keywords = ["django", "blog", "cms", "markdown", "wordpress"]

[project.urls]
Homepage = "https://github.com/stuartmaxwell/djpress"
Documentation = "https://stuartmaxwell.github.io/djpress/"
Repository = "https://github.com/stuartmaxwell/djpress"
Issues = "https://github.com/stuartmaxwell/djpress/issues"

[dependency-groups]
dev = [
  "bumpver~=2026.1132",
  "pre-commit~=4.3",
  "rich~=15.0",
  "ruff~=0.16.5",
]
test = [
  "django-debug-toolbar~=7.1",
  "djpress-example-plugin",
  "nox~=2026.8",
  "pytest~=9.1",
  "pytest-cov~=7.1",
  "pytest-django~=4.14",
  "rich~=15.0",
]
docs = [
  "cogapp~=3.6",
  "furo~=2025.12",
  "myst-parser~=4.0",
  "sphinx~=8.1",
  "sphinx-autobuild~=2024.10",
  "sphinx-copybutton~=0.5",
  "sphinx-rtd-theme~=3.1",
]

[tool.pytest.ini_options]
pythonpath = ". example"
DJANGO_SETTINGS_MODULE = "config.settings_testing"
python_files = "tests.py test_*.py *_tests.py"

[tool.coverage.html]
show_contexts = true

[tool.coverage.run]
branch = true
include = ["src/djpress/*"]
omit = ["*/tests/*", "*/migrations/*"]

[tool.coverage.report]
exclude_lines = ["if TYPE_CHECKING:", "# pragma: no cover"]

[tool.bumpver]
current_version = "0.31.0"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "👍 bump version {old_version} -> {new_version}"
commit = true
push = true
tag = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['version = "{version}"']
"src/djpress/__init__.py" = ['^__version__ = "{version}"$']

[tool.pdm]
distribution = true

[tool.pdm.workspace]
members = ["djpress-example-plugin"]
