name: Deploy Sphinx Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.14"
          cache: true
      - name: Install the project
        run: pdm sync --clean -G docs
      - name: Build documentation
        run: pdm run sphinx-build -b html docs/ docs/_build/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
