name: Run Tests on all Supported Python and Django Versions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.14"
          cache: true
      - name: Install the project
        run: pdm sync --clean -G test
      - name: Run tests
        run: pdm run nox --session test
